#!/usr/bin/env python3
"""Render the Mermaid blocks in docs/ARCHITECTURE.md to SVG files.

No local toolchain needed: each block is encoded and fetched from mermaid.ink.
Run from the repo root:  python3 scripts/render_diagrams.py
Output: docs/diagrams/NN-<slug>.svg  (and an index in docs/diagrams/README.md)
"""
from __future__ import annotations

import base64
import pathlib
import re
import sys
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOC = ROOT / "docs" / "ARCHITECTURE.md"
WIRING = ROOT / "docs" / "WIRING_FOR_DUMMIES.md"
OUT = ROOT / "docs" / "diagrams"
MERMAID_INK = "https://mermaid.ink/svg/"


def slug(text: str, n: int) -> str:
    m = re.search(r"\bgraph\s+\w+|sequenceDiagram|erDiagram", text)
    kind = m.group(0).split()[0] if m else "diagram"
    # first non-empty label-ish word
    label = ""
    mm = re.search(r'\["([^"]+)"', text) or re.search(r"^\s*([A-Za-z][\w /-]{3,})", text, re.M)
    if mm:
        label = re.sub(r"[^a-zA-Z0-9]+", "-", mm.group(1)).strip("-").lower()[:32]
    return f"{n:02d}-{kind.lower()}-{label}".strip("-")


def render(code: str) -> bytes:
    b64 = base64.urlsafe_b64encode(code.encode("utf-8")).decode("ascii")
    req = urllib.request.Request(MERMAID_INK + b64, headers={"User-Agent": "florahome-diagrams"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def main() -> int:
    if not DOC.exists():
        print("missing", DOC)
        return 1
    text = DOC.read_text(encoding="utf-8")
    if WIRING.exists():
        text += "\n" + WIRING.read_text(encoding="utf-8")
    blocks = re.findall(r"```mermaid\n(.*?)```", text, re.S)
    if not blocks:
        print("no mermaid blocks found")
        return 1
    OUT.mkdir(parents=True, exist_ok=True)
    lines = ["# Rendered diagrams", "", "Generated by `scripts/render_diagrams.py` from `docs/ARCHITECTURE.md`.", ""]
    for i, code in enumerate(blocks, 1):
        name = slug(code, i) + ".svg"
        try:
            svg = render(code.strip())
        except Exception as exc:  # noqa: BLE001
            print(f"  ! block {i} failed: {exc}")
            continue
        (OUT / name).write_bytes(svg)
        print(f"  wrote docs/diagrams/{name} ({len(svg)} bytes)")
        lines.append(f"- [`{name}`]({name})")
    (OUT / "README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("done")
    return 0


if __name__ == "__main__":
    sys.exit(main())
